stages:
  - 'lint'
  - 'test'
  - 'build'
  - 'package'
  - 'deploy'

default:
  image: 'docker.io/alpine:latest'

lint-shellcheck-stable:
  stage: 'lint'
  image: 'docker.io/koalaman/shellcheck-alpine:stable'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'shellcheck --version'
  script:
    - 'make lint'

test-debian-latest:
  stage: 'test'
  image: 'docker.io/debian:latest'
  before_script:
    - 'apt-get update'
    - 'apt-get install -y ca-certificates curl file idn2 make'
  script:
    - 'make test'

test-ubuntu-latest:
  stage: 'test'
  image: 'docker.io/ubuntu:latest'
  before_script:
    - 'apt-get update'
    - 'apt-get install -y ca-certificates curl file idn2 make'
  script:
    - 'make test'

test-fedora-latest:
  stage: 'test'
  image: 'docker.io/fedora:latest'
  before_script:
    - 'dnf install -y ca-certificates curl findutils file idn2 make'
  script:
    - 'make test'

test-centos-latest:
  stage: 'test'
  image: 'docker.io/centos:latest'
  before_script:
    - 'dnf install -y ca-certificates curl findutils file idn2 make'
  script:
    - 'make test'

test-opensuse-latest:
  stage: 'test'
  image: 'docker.io/opensuse/leap:latest'
  before_script:
    - 'zypper install -y ca-certificates curl file gzip libidn2-tools make tar'
  script:
    - 'make test'

test-archlinux-latest:
  stage: 'test'
  image: 'docker.io/archlinux:latest'
  before_script:
    - 'pacman -Sy --noconfirm --needed ca-certificates curl file libidn2 make'
  script:
    - 'make test'

test-alpine-edge-bash:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache bash'
    - 'apk info --no-cache bash'
  script:
    - 'make test TEST_SHELL="$(command -v bash)"'

test-alpine-edge-zsh:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache zsh'
    - 'apk info --no-cache zsh'
  script:
    - 'make test TEST_SHELL="$(command -v zsh)"'

test-alpine-edge-dash:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache dash'
    - 'apk info --no-cache dash'
  script:
    - 'make test TEST_SHELL="$(command -v dash)"'

test-alpine-edge-mksh:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache mksh'
    - 'apk info --no-cache mksh'
  script:
    - 'make test TEST_SHELL="$(command -v mksh)"'

test-alpine-edge-oksh:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing oksh'
    - 'apk info --no-cache oksh'
  script:
    - 'make test TEST_SHELL="$(command -v oksh)"'

test-alpine-edge-yash:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache yash'
    - 'apk info --no-cache yash'
  script:
    - 'make test TEST_SHELL="$(command -v yash)"'

test-alpine-edge-busybox-ash:
  stage: 'test'
  image: 'docker.io/alpine:edge'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
    - 'apk add --no-cache busybox'
    - 'apk info --no-cache busybox'
  script:
    - 'make test TEST_SHELL="$(command -v busybox) ash"'

test-openwrt-latest-busybox-ash:
  stage: 'test'
  image: 'docker.io/openwrtorg/rootfs:latest'
  before_script:
    - 'mkdir -p /var/lock/; opkg update'
    - 'opkg install ca-certificates curl file idn2 make'
    - 'opkg install busybox'
    - 'opkg info busybox'
  script:
    - 'make test TEST_SHELL="$(command -v busybox) ash"'

build-debian-latest:
  stage: 'build'
  image: 'docker.io/debian:latest'
  before_script:
    - 'apt-get update'
    - 'apt-get install -y ca-certificates curl file idn2 make'
  script:
    - 'make build stats index'
    - 'mv ./dist/ ./dist-build-debian-latest/'
  artifacts:
    expire_in: '1 day'
    paths: ['./dist-build-debian-latest/']

package-deb:
  stage: 'package'
  image: 'docker.io/debian:latest'
  before_script:
    - 'apt-get update'
    - 'apt-get install -y ca-certificates curl file idn2 make'
    - 'apt-get install -y build-essential debhelper dh-systemd dpkg-dev'
  script:
    - 'make package-deb'
    - 'mv ./dist/ ./dist-package-deb/'
    - 'apt install -y ./dist-package-deb/hblock-*.deb'
    - 'command hblock -v'
  artifacts:
    expire_in: '1 day'
    paths: ['./dist-package-deb/']

package-rpm:
  stage: 'package'
  image: 'docker.io/fedora:latest'
  before_script:
    - 'dnf install -y ca-certificates curl file libidn2 make'
    - 'dnf install -y rpm-build rpmdevtools systemd'
  script:
    - 'make package-rpm'
    - 'mv ./dist/ ./dist-package-rpm/'
    - 'dnf install -y ./dist-package-rpm/hblock-*.rpm'
    - 'command hblock -v'
  artifacts:
    expire_in: '1 day'
    paths: ['./dist-package-rpm/']

package-npm:
  stage: 'package'
  image: 'docker.io/node:current-alpine'
  before_script:
    - 'apk add --no-cache ca-certificates curl file libidn2 make'
  script:
    - 'make package-npm'
    - 'mv ./dist/ ./dist-package-npm/'
    - 'npm install -g ./dist-package-npm/hblock-*.tgz'
    - 'command hblock -v'
  artifacts:
    expire_in: '1 day'
    paths: ['./dist-package-npm/']

pages:
  stage: 'deploy'
  only: ['master']
  script:
    - 'mv ./dist-build-debian-latest/ ./public/'
  artifacts:
    paths: ['./public/']
