name: 'Build'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:

  build-debian-latest:
    name: 'Build on latest Debian'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/debian:latest'
    steps:
      - name: 'Install packages'
        run: 'apt-get update && apt-get install -y ca-certificates curl file findutils grep gzip idn2 make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-ubuntu-latest:
    name: 'Build on latest Ubuntu'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/ubuntu:latest'
    steps:
      - name: 'Install packages'
        run: 'apt-get update && apt-get install -y ca-certificates curl file findutils grep gzip idn2 make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-fedora-latest:
    name: 'Build on latest Fedora'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/fedora:latest'
    steps:
      - name: 'Install packages'
        run: 'dnf install -y ca-certificates curl file findutils grep gzip libidn2 make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-centos-latest:
    name: 'Build on latest CentOS'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/centos:latest'
    steps:
      - name: 'Install packages'
        run: 'dnf install -y ca-certificates curl file findutils grep gzip libidn2 make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-opensuse-latest:
    name: 'Build on latest openSUSE'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/opensuse/tumbleweed:latest'
    steps:
      - name: 'Install packages'
        run: 'zypper install -y ca-certificates curl file findutils grep gzip libidn2-tools make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-archlinux-latest:
    name: 'Build on latest Arch Linux'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/archlinux:latest'
    steps:
      - name: 'Install packages'
        run: 'pacman -Sy --noconfirm --needed ca-certificates curl file findutils grep gzip libidn2 make nawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-alpine-latest:
    name: 'Build on latest Alpine'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/alpine:latest'
    steps:
      - name: 'Install packages'
        run: 'apk add --no-cache ca-certificates curl file findutils grep gzip libidn2 make mawk sed tar zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'

  build-macos-latest:
    name: 'Build on latest macOS'
    runs-on: 'macos-latest'
    steps:
      - name: 'Install packages'
        run: 'brew install curl libidn2 make zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make clean all'
