name: 'Build'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:

  build-debian-latest:
    name: 'Build on Debian'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/debian:latest'
    steps:
      - name: 'Update package index'
        run: 'apt-get update'
      - name: 'Install packages'
        run: 'apt-get install -y ca-certificates curl file idn2 make'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Build project'
        run: 'make build stats index'
