name: 'Lint'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:

  lint-shellcheck-stable:
    name: 'Lint with stable ShellCheck'
    runs-on: 'ubuntu-latest'
    container:
      image: 'docker.io/koalaman/shellcheck-alpine:stable'
    steps:
      - name: 'Install packages'
        run: 'apk add --no-cache ca-certificates curl file libidn2 make zip'
      - name: 'Checkout project'
        uses: 'actions/checkout@main'
      - name: 'Print ShellCheck version'
        run: 'shellcheck --version'
      - name: 'Lint project'
        run: 'make clean lint'
